services:
  db:
    image: postgres:16
    container_name: webshop_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webshop
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - webshop-net

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: webshop_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/webshop
      PORT: 3000
      JWT_ACCESS_SECRET: mySuperSecretAccessKey
      JWT_ACCESS_EXPIRATION: 60
    depends_on:
      - db
    networks:
      - webshop-net

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: webshop_frontend
    restart: always
    ports:
      - "1337:1337"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - webshop-net

  mailpit:
    image: axllent/mailpit
    container_name: webshop_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data
    networks:
      - webshop-net

volumes:
  db_data:
  mailpit_data:

networks:
  webshop-net:
    driver: bridge
