INSERT INTO products (seller_id, name, description, category_id, price, stock, created_at) VALUES
(6, 'Wuffington', 'Ein fröhlicher Pixelhund mit wedelndem Schwanz.', 7, 955.69, 12, CURRENT_TIMESTAMP),
(7, 'Barkley', 'Verspielter Pixelhund, bereit zum Abenteuer.', 7, 999.35, 10, CURRENT_TIMESTAMP),
(8, 'Pixelpup', 'Treuer Begleiter in lebendiger Pixelkunst.', 7, 893.65, 7, CURRENT_TIMESTAMP),
(9, 'Fellbert', 'Bunter Pixelhund mit charmanten Details.', 7, 644.61, 9, CURRENT_TIMESTAMP),
(10, 'Snoutsey', 'Einzigartiger Pixelhund mit großen Augen.', 7, 527.95, 8, CURRENT_TIMESTAMP),
(6, 'Schnurrli', 'Pixelkatze mit flauschigen Schnurrhaaren.', 6, 377.99, 15, CURRENT_TIMESTAMP),
(7, 'Miezarella', 'Neugierige Pixelkatze auf leisen Pfoten.', 6, 711.17, 10, CURRENT_TIMESTAMP),
(8, 'Flauschi', 'Verspielte Pixelkatze mit lebendigen Farben.', 6, 195.53, 9, CURRENT_TIMESTAMP),
(9, 'Kratzbert', 'Pixelkätzchen mit funkelnden Augen.', 6, 734.33, 11, CURRENT_TIMESTAMP),
(10, 'Tigerella', 'Elegante Pixelkatze mit Streifenmuster.', 6, 610.60, 10, CURRENT_TIMESTAMP),
(6, 'Rüsselbert', 'Sanfter Riese in farbenfroher Pixelkunst.', 8, 857.71, 5, CURRENT_TIMESTAMP),
(7, 'Pixelphant', 'Majestätischer Elefant mit langen Stoßzähnen.', 8, 492.77, 6, CURRENT_TIMESTAMP),
(8, 'Trunky', 'Großer Pixel-Elefant voller Charme.', 8, 912.18, 4, CURRENT_TIMESTAMP),
(9, 'Elepixel', 'Pixelierter Elefant mit weichen Konturen.', 8, 583.11, 5, CURRENT_TIMESTAMP),
(10, 'Grautusk', 'Seltene Pixelkunst eines mächtigen Elefanten.', 8, 652.43, 3, CURRENT_TIMESTAMP),
(6, 'Flügelschlag', 'Bunter Pixel-Schmetterling im Flug.', 9, 382.96, 18, CURRENT_TIMESTAMP),
(7, 'Summser', 'Pixel-Biene mit emsigen Flügeln.', 9, 735.50, 14, CURRENT_TIMESTAMP),
(8, 'Pünktchen', 'Pixel-Marienkäfer auf grüner Blätterwelt.', 9, 841.83, 13, CURRENT_TIMESTAMP),
(9, 'Glitzerkäfer', 'Funkelnder Pixel-Käfer mit Charme.', 9, 761.66, 15, CURRENT_TIMESTAMP),
(10, 'Lichtflitzer', 'Pixel-Drachenfliege auf nächtlicher Reise.', 9, 397.02, 12, CURRENT_TIMESTAMP),
(6, 'Farbschleier', 'Lebendige abstrakte Pixelkomposition.', 10, 641.44, 7, CURRENT_TIMESTAMP),
(7, 'Formenspiel', 'Moderne Pixelkunst mit faszinierenden Formen.', 10, 832.90, 6, CURRENT_TIMESTAMP),
(8, 'Pixelrausch', 'Abstrakte Pixelwelt voller Farben und Linien.', 10, 506.24, 8, CURRENT_TIMESTAMP),
(9, 'Strukturtraum', 'Einzigartige abstrakte Pixelgestaltung.', 10, 961.88, 5, CURRENT_TIMESTAMP),
(10, 'Chaosfarben', 'Farbenfrohe abstrakte Pixelkomposition.', 10, 875.52, 9, CURRENT_TIMESTAMP),
(6, 'Barrel Bouncer', 'Klassischer Pixel-Donkey Kong in Aktion.', 11, 694.31, 4, CURRENT_TIMESTAMP),
(7, 'Kong Smash', 'Seltener Pixel-Donkey Kong mit Power.', 11, 812.70, 3, CURRENT_TIMESTAMP),
(8, 'Jungle King', 'Vintage Donkey Kong Pixelkunst.', 11, 933.19, 6, CURRENT_TIMESTAMP),
(9, 'Barrel Thrower', 'Pixel-Donkey Kong mit markanten Fässern.', 11, 769.82, 5, CURRENT_TIMESTAMP),
(10, 'Pixel Kong', 'Dynamischer Donkey Kong in Pixelform.', 11, 827.23, 4, CURRENT_TIMESTAMP),
(6, 'King of Pixels', 'Donkey Kong Pixelkunst mit Stil.', 11, 902.56, 7, CURRENT_TIMESTAMP),
(7, 'Jumpman', 'Klassischer Mario in lebendigen Pixeln.', 12, 688.45, 8, CURRENT_TIMESTAMP),
(8, 'Pixel Plumber', 'Mario mit legendärer Mütze.', 12, 736.61, 6, CURRENT_TIMESTAMP),
(9, 'Stomp Champ', 'Pixel Mario in voller Aktion.', 12, 958.01, 9, CURRENT_TIMESTAMP),
(10, 'Mushroom Master', 'Pixelart von Mario mit Pilz.', 12, 775.04, 5, CURRENT_TIMESTAMP),
(6, 'Red Racer', 'Vintage Mario in Pixeloptik.', 12, 889.12, 7, CURRENT_TIMESTAMP),
(7, 'Pixel Jumper', 'Mario rennt in Pixelwelt.', 12, 845.37, 6, CURRENT_TIMESTAMP),
(8, 'Blocky Builder', 'Pixelige Minecraft-Welt in Farben.', 13, 592.43, 10, CURRENT_TIMESTAMP),
(9, 'Pixel Miner', 'Minecraft-Charakter in Pixeln.', 13, 624.30, 8, CURRENT_TIMESTAMP),
(10, 'Pixelmon', 'Pixelkunst eines beliebten Pokemon.', 14, 710.55, 7, CURRENT_TIMESTAMP),
(6, 'Pikapixel', 'Klassisches Pokemon im Pixelstil.', 14, 897.33, 6, CURRENT_TIMESTAMP),
(7, 'Pokepix', 'Pixelierter Pokemon-Charakter.', 14, 665.87, 9, CURRENT_TIMESTAMP),
(8, 'RarePixelmon', 'Seltenes Pixel-Pokemon.', 14, 774.12, 5, CURRENT_TIMESTAMP),
(9, 'Pixelchu', 'Charmantes Pokemon in Pixeln.', 14, 682.40, 7, CURRENT_TIMESTAMP),
(10, 'Pixelzap', 'Pixel-Pokemon mit Energie.', 14, 799.21, 8, CURRENT_TIMESTAMP),
(6, 'Speedster', 'Schneller Pixel-Sonic.', 15, 915.35, 9, CURRENT_TIMESTAMP),
(7, 'Blue Blur', 'Klassischer Sonic in Pixeln.', 15, 870.99, 8, CURRENT_TIMESTAMP),
(8, 'Spin Dash', 'Pixel-Sonic in Aktion.', 15, 813.76, 7, CURRENT_TIMESTAMP),
(9, 'Soul Pixel', 'Pixelart aus Undertale.', 16, 954.62, 5, CURRENT_TIMESTAMP),
(10, 'Determination', 'Einzigartiger Undertale-Pixel.', 16, 921.84, 6, CURRENT_TIMESTAMP),
(6, 'Pixel Flowey', 'Vintage Undertale-Pixelkunst.', 16, 890.01, 7, CURRENT_TIMESTAMP),
(7, 'Undertale Hero', 'Pixelheld aus Undertale.', 16, 872.42, 4, CURRENT_TIMESTAMP),
(8, 'Chara Pixel', 'Seltene Undertale-Pixelkunst.', 16, 923.77, 8, CURRENT_TIMESTAMP),
(9, 'Sans Pixel', 'Pixel-Figur aus Undertale.', 16, 959.36, 9, CURRENT_TIMESTAMP),
(6, 'Pixel Panorama', 'Wunderschöne Pixel-Landschaft.', 17, 684.45, 7, CURRENT_TIMESTAMP),
(7, 'Mountain Glow', 'Pixel-Berglandschaft bei Sonnenuntergang.', 17, 702.81, 6, CURRENT_TIMESTAMP),
(8, 'Forest Whisper', 'Pixelwald in leuchtenden Farben.', 17, 728.35, 8, CURRENT_TIMESTAMP),
(9, 'Sunset Glow', 'Pixel-Sonnenuntergang über den Hügeln.', 17, 790.64, 5, CURRENT_TIMESTAMP),
(10, 'Riverbend', 'Pixel-Flusslandschaft mit ruhiger Atmosphäre.', 17, 673.92, 9, CURRENT_TIMESTAMP),
(6, 'Wave Rider', 'Pixelige Ozeanwellen in Bewegung.', 18, 834.15, 10, CURRENT_TIMESTAMP),
(7, 'Beach Breeze', 'Pixelstrand mit sanfter Brise.', 18, 703.98, 7, CURRENT_TIMESTAMP),
(8, 'Deep Dive', 'Pixel-Unterwasserwelt voller Leben.', 18, 752.31, 8, CURRENT_TIMESTAMP),
(9, 'Seashore Shine', 'Pixelstrand bei Sonnenlicht.', 18, 688.74, 6, CURRENT_TIMESTAMP),
(10, 'Ocean Sunset', 'Pixel-Sonnenuntergang am Meer.', 18, 714.90, 5, CURRENT_TIMESTAMP),
(6, 'Blue Horizon', 'Pixelblauer Himmel mit Wolken.', 19, 639.11, 9, CURRENT_TIMESTAMP),
(7, 'Crimson Dusk', 'Pixel-Himmel bei Sonnenuntergang.', 19, 701.26, 8, CURRENT_TIMESTAMP),
(8, 'Midnight Glow', 'Pixelnacht mit Sternenhimmel.', 19, 789.45, 7, CURRENT_TIMESTAMP),
(9, 'Cloud Drift', 'Pixelwolken schweben am Himmel.', 19, 755.87, 6, CURRENT_TIMESTAMP),
(6, 'Sky Vista', 'Dynamischer Himmel in pixeliger Brillanz.', 19, 832.68, 12, CURRENT_TIMESTAMP),
(7, 'Dystopia Rise', 'Düstere pixelige Stadtlandschaft einer Zukunftsvision.', 20, 901.22, 8, CURRENT_TIMESTAMP),
(8, 'Urban Collapse', 'Verlassene Gebäude und leere Straßen im Pixelstil.', 20, 878.90, 7, CURRENT_TIMESTAMP),
(9, 'Dark Horizon', 'Bedrohliche Skyline in dystopischem Pixel-Design.', 20, 934.55, 9, CURRENT_TIMESTAMP),
(10, 'Neon Shadows', 'Postapokalyptische Stadt mit dunklem Neon-Glanz.', 20, 849.33, 5, CURRENT_TIMESTAMP),
(6, 'Last Refuge', 'Letzter Zufluchtsort in einer zerstörten Pixel-Welt.', 20, 798.77, 6, CURRENT_TIMESTAMP),
(7, 'Future District', 'Futuristische Metropole im retro-pixel Look.', 21, 892.16, 10, CURRENT_TIMESTAMP),
(8, 'Tech Core', 'Zentrum einer hochtechnisierten Pixel-Stadt.', 21, 911.24, 7, CURRENT_TIMESTAMP),
(9, 'Neon Tower', 'Leuchtende Türme in futuristischem Pixelstil.', 21, 939.88, 4, CURRENT_TIMESTAMP),
(10, 'Cyberview', 'Blick über eine vernetzte Pixelstadt der Zukunft.', 21, 866.34, 11, CURRENT_TIMESTAMP),
(6, 'Mech Bay', 'Mechanische Hafenstadt in Pixeldetails.', 21, 845.60, 6, CURRENT_TIMESTAMP),
(7, 'Skyline Dreams', 'Moderne Pixel-Skyline bei Dämmerung.', 22, 921.90, 13, CURRENT_TIMESTAMP),
(8, 'Urban Glow', 'Pixelstadt mit glänzenden Hochhäusern bei Nacht.', 22, 888.25, 9, CURRENT_TIMESTAMP),
(9, 'City Grid', 'Geordnete Architektur einer Stadt im Rasterdesign.', 22, 769.43, 5, CURRENT_TIMESTAMP),
(10, 'Mirror Towers', 'Symmetrische Wolkenkratzer in pixeliger Perspektive.', 22, 934.80, 8, CURRENT_TIMESTAMP),
(6, 'Urban Lights', 'Belebte Skyline mit leuchtenden Fenstern in Pixel-Art.', 22, 982.55, 10, CURRENT_TIMESTAMP);
