INSERT INTO products (seller_id, name, description, category_id, price, stock, created_at) VALUES
(6, 'Wuffington', 'Ein fröhlicher Pixelhund mit wedelndem Schwanz.', 7, 45.99, 12, CURRENT_TIMESTAMP),
(7, 'Barkley', 'Verspielter Pixelhund, bereit zum Abenteuer.', 7, 52.30, 10, CURRENT_TIMESTAMP),
(8, 'Pixelpup', 'Treuer Begleiter in lebendiger Pixelkunst.', 7, 48.75, 7, CURRENT_TIMESTAMP),
(9, 'Fellbert', 'Bunter Pixelhund mit charmanten Details.', 7, 50.20, 9, CURRENT_TIMESTAMP),
(10, 'Snoutsey', 'Einzigartiger Pixelhund mit großen Augen.', 7, 47.00, 8, CURRENT_TIMESTAMP),
(6, 'Schnurrli', 'Pixelkatze mit flauschigen Schnurrhaaren.', 6, 38.45, 15, CURRENT_TIMESTAMP),
(7, 'Miezarella', 'Neugierige Pixelkatze auf leisen Pfoten.', 6, 41.00, 10, CURRENT_TIMESTAMP),
(8, 'Flauschi', 'Verspielte Pixelkatze mit lebendigen Farben.', 6, 40.75, 9, CURRENT_TIMESTAMP),
(9, 'Kratzbert', 'Pixelkätzchen mit funkelnden Augen.', 6, 39.50, 11, CURRENT_TIMESTAMP),
(10, 'Tigerella', 'Elegante Pixelkatze mit Streifenmuster.', 6, 42.30, 10, CURRENT_TIMESTAMP),
(6, 'Rüsselbert', 'Sanfter Riese in farbenfroher Pixelkunst.', 8, 60.99, 5, CURRENT_TIMESTAMP),
(7, 'Pixelphant', 'Majestätischer Elefant mit langen Stoßzähnen.', 8, 63.50, 6, CURRENT_TIMESTAMP),
(8, 'Trunky', 'Großer Pixel-Elefant voller Charme.', 8, 61.75, 4, CURRENT_TIMESTAMP),
(9, 'Elepixel', 'Pixelierter Elefant mit weichen Konturen.', 8, 62.20, 5, CURRENT_TIMESTAMP),
(10, 'Grautusk', 'Seltene Pixelkunst eines mächtigen Elefanten.', 8, 64.00, 3, CURRENT_TIMESTAMP),
(6, 'Flügelschlag', 'Bunter Pixel-Schmetterling im Flug.', 9, 29.99, 18, CURRENT_TIMESTAMP),
(7, 'Summser', 'Pixel-Biene mit emsigen Flügeln.', 9, 31.20, 14, CURRENT_TIMESTAMP),
(8, 'Pünktchen', 'Pixel-Marienkäfer auf grüner Blätterwelt.', 9, 28.75, 13, CURRENT_TIMESTAMP),
(9, 'Glitzerkäfer', 'Funkelnder Pixel-Käfer mit Charme.', 9, 30.50, 15, CURRENT_TIMESTAMP),
(10, 'Lichtflitzer', 'Pixel-Drachenfliege auf nächtlicher Reise.', 9, 32.00, 12, CURRENT_TIMESTAMP),
(6, 'Farbschleier', 'Lebendige abstrakte Pixelkomposition.', 10, 55.00, 7, CURRENT_TIMESTAMP),
(7, 'Formenspiel', 'Moderne Pixelkunst mit faszinierenden Formen.', 10, 57.20, 6, CURRENT_TIMESTAMP),
(8, 'Pixelrausch', 'Abstrakte Pixelwelt voller Farben und Linien.', 10, 54.75, 8, CURRENT_TIMESTAMP),
(9, 'Strukturtraum', 'Einzigartige abstrakte Pixelgestaltung.', 10, 56.50, 5, CURRENT_TIMESTAMP),
(10, 'Chaosfarben', 'Farbenfrohe abstrakte Pixelkomposition.', 10, 58.00, 9, CURRENT_TIMESTAMP),
(6, 'Barrel Bouncer', 'Klassischer Pixel-Donkey Kong in Aktion.', 11, 120.00, 4, CURRENT_TIMESTAMP),
(7, 'Kong Smash', 'Seltener Pixel-Donkey Kong mit Power.', 11, 130.50, 3, CURRENT_TIMESTAMP),
(8, 'Jungle King', 'Vintage Donkey Kong Pixelkunst.', 11, 125.75, 6, CURRENT_TIMESTAMP),
(9, 'Barrel Thrower', 'Pixel-Donkey Kong mit markanten Fässern.', 11, 128.00, 5, CURRENT_TIMESTAMP),
(10, 'Pixel Kong', 'Dynamischer Donkey Kong in Pixelform.', 11, 132.20, 4, CURRENT_TIMESTAMP),
(6, 'King of Pixels', 'Donkey Kong Pixelkunst mit Stil.', 11, 129.00, 7, CURRENT_TIMESTAMP),
(7, 'Jumpman', 'Klassischer Mario in lebendigen Pixeln.', 12, 115.00, 8, CURRENT_TIMESTAMP),
(8, 'Pixel Plumber', 'Mario mit legendärer Mütze.', 12, 118.20, 6, CURRENT_TIMESTAMP),
(9, 'Stomp Champ', 'Pixel Mario in voller Aktion.', 12, 120.50, 9, CURRENT_TIMESTAMP),
(10, 'Mushroom Master', 'Pixelart von Mario mit Pilz.', 12, 122.00, 5, CURRENT_TIMESTAMP),
(6, 'Red Racer', 'Vintage Mario in Pixeloptik.', 12, 117.50, 7, CURRENT_TIMESTAMP),
(7, 'Pixel Jumper', 'Mario rennt in Pixelwelt.', 12, 119.75, 6, CURRENT_TIMESTAMP),
(8, 'Blocky Builder', 'Pixelige Minecraft-Welt in Farben.', 13, 85.00, 10, CURRENT_TIMESTAMP),
(9, 'Pixel Miner', 'Minecraft-Charakter in Pixeln.', 13, 87.20, 8, CURRENT_TIMESTAMP),
(10, 'Pixelmon', 'Pixelkunst eines beliebten Pokemon.', 14, 110.00, 7, CURRENT_TIMESTAMP),
(6, 'Pikapixel', 'Klassisches Pokemon im Pixelstil.', 14, 112.30, 6, CURRENT_TIMESTAMP),
(7, 'Pokepix', 'Pixelierter Pokemon-Charakter.', 14, 113.50, 9, CURRENT_TIMESTAMP),
(8, 'RarePixelmon', 'Seltenes Pixel-Pokemon.', 14, 115.75, 5, CURRENT_TIMESTAMP),
(9, 'Pixelchu', 'Charmantes Pokemon in Pixeln.', 14, 111.20, 7, CURRENT_TIMESTAMP),
(10, 'Pixelzap', 'Pixel-Pokemon mit Energie.', 14, 114.00, 8, CURRENT_TIMESTAMP),
(6, 'Speedster', 'Schneller Pixel-Sonic.', 15, 95.00, 9, CURRENT_TIMESTAMP),
(7, 'Blue Blur', 'Klassischer Sonic in Pixeln.', 15, 96.50, 8, CURRENT_TIMESTAMP),
(8, 'Spin Dash', 'Pixel-Sonic in Aktion.', 15, 94.75, 7, CURRENT_TIMESTAMP),
(9, 'Soul Pixel', 'Pixelart aus Undertale.', 16, 105.00, 5, CURRENT_TIMESTAMP),
(10, 'Determination', 'Einzigartiger Undertale-Pixel.', 16, 108.25, 6, CURRENT_TIMESTAMP),
(6, 'Pixel Flowey', 'Vintage Undertale-Pixelkunst.', 16, 107.50, 7, CURRENT_TIMESTAMP),
(7, 'Undertale Hero', 'Pixelheld aus Undertale.', 16, 106.75, 4, CURRENT_TIMESTAMP),
(8, 'Chara Pixel', 'Seltene Undertale-Pixelkunst.', 16, 109.00, 8, CURRENT_TIMESTAMP),
(9, 'Sans Pixel', 'Pixel-Figur aus Undertale.', 16, 110.20, 9, CURRENT_TIMESTAMP),
(6, 'Pixel Panorama', 'Wunderschöne Pixel-Landschaft.', 17, 75.00, 7, CURRENT_TIMESTAMP),
(7, 'Mountain Glow', 'Pixel-Berglandschaft bei Sonnenuntergang.', 17, 77.20, 6, CURRENT_TIMESTAMP),
(8, 'Forest Whisper', 'Pixelwald in leuchtenden Farben.', 17, 74.50, 8, CURRENT_TIMESTAMP),
(9, 'Sunset Glow', 'Pixel-Sonnenuntergang über den Hügeln.', 17, 76.80, 5, CURRENT_TIMESTAMP),
(10, 'Riverbend', 'Pixel-Flusslandschaft mit ruhiger Atmosphäre.', 17, 78.00, 9, CURRENT_TIMESTAMP),
(6, 'Wave Rider', 'Pixelige Ozeanwellen in Bewegung.', 18, 69.00, 10, CURRENT_TIMESTAMP),
(7, 'Beach Breeze', 'Pixelstrand mit sanfter Brise.', 18, 70.50, 7, CURRENT_TIMESTAMP),
(8, 'Deep Dive', 'Pixel-Unterwasserwelt voller Leben.', 18, 68.75, 8, CURRENT_TIMESTAMP),
(9, 'Seashore Shine', 'Pixelstrand bei Sonnenlicht.', 18, 67.80, 6, CURRENT_TIMESTAMP),
(10, 'Ocean Sunset', 'Pixel-Sonnenuntergang am Meer.', 18, 71.00, 5, CURRENT_TIMESTAMP),
(6, 'Blue Horizon', 'Pixelblauer Himmel mit Wolken.', 19, 50.00, 9, CURRENT_TIMESTAMP),
(7, 'Crimson Dusk', 'Pixel-Himmel bei Sonnenuntergang.', 19, 52.30, 8, CURRENT_TIMESTAMP),
(8, 'Midnight Glow', 'Pixelnacht mit Sternenhimmel.', 19, 51.20, 7, CURRENT_TIMESTAMP),
(9, 'Cloud Drift', 'Pixelwolken schweben am Himmel.', 19, 53.50, 6, CURRENT_TIMESTAMP),
(6, 'Sky Vista', 'Dynamischer Himmel in pixeliger Brillanz.', 19, 69.00, 12, CURRENT_TIMESTAMP),
(7, 'Dystopia Rise', 'Düstere pixelige Stadtlandschaft einer Zukunftsvision.', 20, 70.20, 8, CURRENT_TIMESTAMP),
(8, 'Urban Collapse', 'Verlassene Gebäude und leere Straßen im Pixelstil.', 20, 68.90, 7, CURRENT_TIMESTAMP),
(9, 'Dark Horizon', 'Bedrohliche Skyline in dystopischem Pixel-Design.', 20, 71.30, 9, CURRENT_TIMESTAMP),
(10, 'Neon Shadows', 'Postapokalyptische Stadt mit dunklem Neon-Glanz.', 20, 67.80, 5, CURRENT_TIMESTAMP),
(6, 'Last Refuge', 'Letzter Zufluchtsort in einer zerstörten Pixel-Welt.', 20, 72.00, 6, CURRENT_TIMESTAMP),
(7, 'Future District', 'Futuristische Metropole im retro-pixel Look.', 21, 69.50, 10, CURRENT_TIMESTAMP),
(8, 'Tech Core', 'Zentrum einer hochtechnisierten Pixel-Stadt.', 21, 70.80, 7, CURRENT_TIMESTAMP),
(9, 'Neon Tower', 'Leuchtende Türme in futuristischem Pixelstil.', 21, 68.40, 4, CURRENT_TIMESTAMP),
(10, 'Cyberview', 'Blick über eine vernetzte Pixelstadt der Zukunft.', 21, 73.20, 11, CURRENT_TIMESTAMP),
(6, 'Mech Bay', 'Mechanische Hafenstadt in Pixeldetails.', 21, 66.90, 6, CURRENT_TIMESTAMP),
(7, 'Skyline Dreams', 'Moderne Pixel-Skyline bei Dämmerung.', 22, 71.75, 13, CURRENT_TIMESTAMP),
(8, 'Urban Glow', 'Pixelstadt mit glänzenden Hochhäusern bei Nacht.', 22, 70.10, 9, CURRENT_TIMESTAMP),
(9, 'City Grid', 'Geordnete Architektur einer Stadt im Rasterdesign.', 22, 69.25, 5, CURRENT_TIMESTAMP),
(10, 'Mirror Towers', 'Symmetrische Wolkenkratzer in pixeliger Perspektive.', 22, 72.90, 8, CURRENT_TIMESTAMP),
(6, 'Urban Lights', 'Belebte Skyline mit leuchtenden Fenstern in Pixel-Art.', 22, 70.50, 10, CURRENT_TIMESTAMP);
